---

# === "EC2-specific installation" ===

- name: Setup AWS Resource Tracker
  hosts: ec2                        # Target group defined in inventory.ini
  become: yes                       # Run tasks with sudo/root privileges
  roles:
    - common
  tasks:
    
    - name: Download and install AWS CLI (v2)
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip -o awscliv2.zip
        sudo ./aws/install
      args:
        creates: /usr/local/bin/aws   # Skip if AWS CLI is already installed at this path

# === "VM-specific installation" ===

- name: Setup Azure VM Resource Tracker
  hosts: vm                        
  become: yes
  roles:
    - common    
  tasks:

    - name: Install Azure CLI
      package:
        name: azure-cli
        state: present

# === "WSL-specific installation" ===

- name: Setup GitHub Resource Tracker
  hosts: wsl
  become: false # Run as regular user to modify ~/.bashrc
  vars_files:
    - vars.yml # Path to secret file
  roles:
    - common
  tasks:

    # OBS! change to use of source and env when CI/CD

    - name: Export GitHub Repo Owner
      lineinfile: # Ensures the line exists in the file (adds or updates)
        path: ~/.bashrc # Adds environment variable to user's bash profile
        line: 'export REPO_OWNER={{ REPO_OWNER }}'
        state: present # Creates the file if it doesn't already exist

    - name: Export GitHub Repo Name
      lineinfile:
        path: ~/.bashrc
        line: 'export REPO_NAME={{ REPO_NAME }}'
        state: present

    - name: Export GitHub Token
      lineinfile:
        path: ~/.bashrc
        line: 'export GITHUB_TOKEN={{ GITHUB_TOKEN }}'
        state: present
